# Generated by Django 5.0.2 on 2024-03-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoFirma',
        ),
        migrations.RemoveField(
            model_name='documentocarga',
            name='tamanio',
        ),
        migrations.AddField(
            model_name='documentocarga',
            name='archivo',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentocarga',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
