# Generated by Django 4.2.11 on 2024-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_delete_documentofirma_remove_documentocarga_tamanio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocarga',
            name='estado',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='documentocarga',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
