# Generated by Django 4.2.11 on 2024-04-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentocarga_estado_documentocarga_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocarga',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
