# Generated by Django 4.2.11 on 2024-05-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_documentocarga_hash_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocarga',
            name='hash_archivo',
        ),
    ]
