# Generated by Django 4.2.11 on 2024-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('role', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': ('usuarios',),
            },
        ),
    ]
