# Generated by Django 4.2.11 on 2024-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(default=None, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('tipo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
