<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-04-13 06:20
=======
# Generated by Django 4.2.11 on 2024-05-01 04:29
>>>>>>> 41fc66c176e26d3cafb8a7ae61f2af14c7fa8cf7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.CharField(),
        ),
    ]
