# Generated by Django 4.2.11 on 2024-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.CharField(),
        ),
    ]
